PointfootCfg:
  loop_frequency: 400 #500
  joint_names:
    - "abad_L_Joint"
    - "hip_L_Joint"
    - "knee_L_Joint"
    - "ankle_L_Joint"
    - "abad_R_Joint"
    - "hip_R_Joint"
    - "knee_R_Joint"
    - "ankle_R_Joint"
    - "J1"
    - "J2"
    - "J3"
    - "J4"
    - "J5"
    - "J6"

  init_state:
    # target angles [rad] when action = 0.0
    default_joint_angle:
      abad_L_Joint: 0.0
      hip_L_Joint: 0.0 #0.13
      knee_L_Joint: 0.0
      ankle_L_Joint: 0.0

      abad_R_Joint: 0.0
      hip_R_Joint: 0.0 #-0.13
      knee_R_Joint: 0.0
      ankle_R_Joint: 0.0
      J1: 0.0
      J2: 0.0
      J3: -0.0
      J4: 0.0
      J5: 0.0
      J6: 0.0

  control:
    # PD Drive parameters:
    stiffness: 45.0
    damping: 3 # 1.5
    ankle_joint_damping: 1.5 # 0.8
    ankle_joint_torque_limit: 20
    action_scale_pos: 0.25
    decimation: 10
    user_torque_limit: 80

  normalization:
    clip_scales:
      clip_observations: 100.
      clip_actions: 100.
    obs_scales:
      lin_vel: 2.0
      ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05

  size:
    actions_size: 14
    observations_size: 54
    obs_history_length: 5
    encoder_output_size: 3
    commands_size: 5

  gait:
    frequencies: 1.3
    swing_height: 0.12

  stand_mode:
    stand_duration: 1.0

  imu_orientation_offset:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  user_cmd_scales:
    lin_vel_x: 1.0
    lin_vel_y: 0.5
    ang_vel_yaw: 1.0
